# Generated by Django 3.2.16 on 2022-12-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='favourites',
            old_name='user_id',
            new_name='user',
        ),
    ]
