# Generated by Django 3.2.16 on 2022-12-13 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trello_app', '0002_auto_20221212_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='date',
            new_name='deadline',
        ),
        migrations.CreateModel(
            name='RecentViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('board', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to='trello_app.board')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
