# Generated by Django 3.2.16 on 2023-01-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0004_auto_20221213_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentviews',
            name='views_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
